### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by NE1W01F** [lucanaef/PGPro#1]
It would be nice to be able to generate PGP keys and store them. Just a suggestion.

**Comment by lucanaef** [comment]
Hi

Thanks for the suggestion. I've added the feature to the roadmap :-)

**Comment by NE1W01F** [comment]
I would help you but i don't have a mac. so i can't write xcode to help out. but i wish you the best

**Comment by lucanaef** [comment]
This feature has been implemented in version 2020.1 🎉 If you have questions or feedback about it, feel free to open another issue here on Github or contact me directly via email. Thanks again for the suggestion.
