### ISSUE TITLE
Проблема 

### ISSUE THREAD

**Issue by Wagner212121** [lucanaef/PGPro#107]
Надо восстановить доступ в аккаунт установил аутевикатор и случайно удалил в приложении аккаунт могу ли я его восторгать ?

**Comment by lucanaef** [comment]
If you haven't created a backup, there is no way to recover your private keys once deleted.

**Comment by Wagner212121** [comment]
A im name in emailОтправлено с iPhone5 февр. 2023 г., в 17:10, Luca Näf ***@***.***> написал(а):﻿
If you haven't created a backup, there is no way to recover your private keys once deleted.

**Comment by Wagner212121** [comment]
Deleted PGP?Отправлено с iPhone5 февр. 2023 г., в 17:10, Luca Näf ***@***.***> написал(а):﻿
If you haven't created a backup, there is no way to recover your private keys once deleted.
