### ISSUE TITLE
'Swipe' gets stuck in Settings page

### ISSUE THREAD

**Issue by MichaelTan9999** [lucanaef/PGPro#16]
On settings page, once you swipe down, you cannot swipe up.

**Comment by lucanaef** [comment]
What device are you using?

**Comment by MichaelTan9999** [comment]
> What device are you using?
iPhone X, A1865, iOS 14.0(18A5319i)
Though it's a public beta iOS, other apps don't show swiping problems 😯
And even if the swiping doesn't work, the buttons on the settings page are able to click.
Thanks for your noticing the bug here!

**Comment by lucanaef** [comment]
I haven't installed the beta yet, but I will keep this in mind and leave the issue open. Thank you!

**Comment by lucanaef** [comment]
I think this has been fixed in the most recent update. If not, please open an issue! Thanks :)
