### ISSUE TITLE
Support keys without e-mail address

### ISSUE THREAD

**Issue by flowmymind** [lucanaef/PGPro#22]
Hey Luca,

thank you for your work. Great app so long, but I had several issues today with adding some public keys. I figured out, that all keys, which were "not supported" by PGPro, didn't combine with an e-mail address. Is it a bug or feature? ;-) Anyway, it would be great to add those keys, wouldn't it?

Thank you!

**Comment by lucanaef** [comment]
I'm not sure why you'd want this, but there is not a great reason not to support it. Will be included in the next update. Please notify me about weird behavior since there could be a few edge cases I missed to define properly.
