### ISSUE TITLE
Unable to decrypt message from Thunderbird

### ISSUE THREAD

**Issue by tom709** [lucanaef/PGPro#23]
Thanks for making PGPro, I think it is a long missing addition to the iOS ecosystem.
However I got one problem: when I receive an encrypted mail sent from Thunderbird 78.3.2 and forward it to PGPro from the built-in iOS Email app, PGPro fails to decrypt it. The error msg is simply "Decryption failed!". I can decrypt other PGP blocks and tracked down the error to the fact, that PGP blocks generated as above are missing an empty line after the line "-----BEGIN PGP MESSAGE-----". This only seems to be the case when I directly forward the "encrypted.asc" MIME attachment from the iOS EMail app to PGPro. When I somehow get the attachment into a text editor and from there copy&paste it to PGPRo, decryption works. Needless to say, the latter is extremely inconvenient on an iOS device ... :-)

**Comment by lucanaef** [comment]
Thanks for letting me know. I'll look into it :-)

**Comment by lucanaef** [comment]
I think I found the bug that caused this issue. Stay tuned 😃

**Comment by lucanaef** [comment]
If possible, could you [join the beta](https://testflight.apple.com/join/BNawuaNF) and verify that this bug has been fixed?

**Comment by lucanaef** [comment]
Fixed in 2020.6
