### ISSUE TITLE
Please Enable iOS 12.4.x Support. App Shows: iOS 13 Required.

### ISSUE THREAD

**Issue by atErik** [lucanaef/PGPro#24]
Hi,  
could not run the app in iOS v12.4.x iPhone-6.

this app or AppStore shows message (after or during install), that,  
iOS v13 or above is needed.  
:(  

Please enable support for iOS v12.4.x / v12 (when time-permits to do so).  
i'm sure, lots of users still using iPhone-6.

**Comment by eutampieri** [comment]
I will have a look if it’s possible

**Comment by eutampieri** [comment]
Excuse me, I cannot find the Xcode project file so I am not able to look into this for now

**Comment by lucanaef** [comment]
The Xcode project files should now all be available if you still want to give it a try. 
I'll close this issue since I don't think I will re-add support for iOS 12. Sorry.
