### ISSUE TITLE
.asc support

### ISSUE THREAD

**Issue by giovannikraushaar** [lucanaef/PGPro#3]
Since files app on iOS is not able to open files with extension .asc as a regular text file nor it allows to rename the extension to .txt, I think it would be great if PGPro was able to import .asc files from iOS's share menu.

**Comment by lucanaef** [comment]
I agree! Thanks for the suggestion, I added the feature to the roadmap.

**Comment by lucanaef** [comment]
This feature has been implemented in version 2020.1  🎉 If you have questions or feedback about it, feel free to open another issue here on Github or contact me directly via email. Thanks again for the suggestion.
