### ISSUE TITLE
.gitignored project files?

### ISSUE THREAD

**Issue by ReDetection** [lucanaef/PGPro#30]
Hello,

I come across this project and would like to get started with it, but unfortunately all the Xcode project files is gitignored. Can you please share why? At the moment I wasn't able to find any reasoning neither in git history, nor on the website. It seems to be added just the second commit to the repo. 

Gitignore file seems to be autogenerated and it is too broad – repo obviously does not contain swift package library, but it has spm artifacts gitignored as well. Xcode gitignore section contains both reasonable lines (like `xcuserdata`) and also lines I find unreasonable to gitignore (like `xcodeproj`). 

In my opinion, whole Xcode section should be discarded and SwiftPM section too, but Swift section kept. In my projects, I usually only have this much:

```
# Mac OS X
.DS_Store

# Backup files
*~.nib

# Xcode
build/*
*.pbxuser
!default.pbxuser
*.mode1v3
!default.mode1v3
*.mode2v3
!default.mode2v3
*.perspectivev3
!default.perspectivev3
*.xccheckout
xcuserdata
profile
*.moved-aside
DerivedData
*.xcscmblueprint

# AppCode
.idea
```

Would you mind sharing xcodeproj (and xcworkspace if any) with the rest of the world please?

**Comment by lucanaef** [comment]
The reason I exluded xcodeproj was, that I wasn't sure it doesn't contain any sensitive information (e.g. signing certificate data, etc.). If that's not the case, I'll happily share it :-)
The rest of the .gitignore file has indeed be autogenerated, but I think is fine.

**Comment by ReDetection** [comment]
Thanks for the response :) xcodeproj is safe in the way it does not have any key embedded in, it only has references on how to find one. Project file is just a very long text file so you can open in any text editor including Xcode itself and verify. In terms of app distribution, it only contains:
* Team ID (you can find for `DevelopmentTeam` text in the file), which is used to find proper Certificate and Private key in your Keychain app
* Provisioning profile (either it's UUID, or it's name – look for `PROVISIONING_PROFILE`) to embed into the app so devices can verify if they can trust and run the app. Actual profiles are stored in the `~/Library/MobileDevice/Provisioning Profiles` directory on your machine and basically they are useless without the private key

Both of these are safe to share because they are only references. Maybe if you use feature to Automatically manage signing in Xcode, then maybe they are not even exist in the project file, this I never checked.  

So as long as you do not put any other special private key-alike stuff into the build settings or build phases, then you should be safe.  :)

**Comment by lucanaef** [comment]
I've just pushed the project file

**Comment by ReDetection** [comment]
Thanks a lot! I can confirm project files is now there, so the issue is resolved. With #32 and https://github.com/Yubico/yubikit-ios/pull/62 merged, the code is able to build 👍
