### ISSUE TITLE
Add support for OpenKeychain (Android) QR Codes

### ISSUE THREAD

**Issue by reinhart1010** [lucanaef/PGPro#48]
The [OpenKeychain](https://www.openkeychain.org/) QR code simply contains a plaintext string with the format `OPENPGP4FPR:<Fingerprint>`.

Here's an example of the generated QR code for Edward, an email bot from the FSF to test email encryption (as in emailselfdefense.fsf.org).

![Screenshot_20210601-015552_OpenKeychain.jpg](https://user-images.githubusercontent.com/17312341/120262342-c4236f80-c2c3-11eb-82ed-b23f8f11ad8d.jpg)
 `OPENPGP4FPR:F357AA1A5B1FA42CFD9FE52A9FF2194CC09A61E8`.

Adding the ability to scan the QR code would be a great way to instantly add another public key without the need of manually enter an email or the fingerprint into the app. This can be done by:

1. Scanning the QR code
2. Check whether the payload is valid
3. Search signature on keyservers

The OpenKeychain app also uses this functionality to verify confirm other public keys, if the current private key is capable of confirming other keys (aka. unstripped).

![Screenshot_20210601-104629_OpenKeychain.jpg](https://user-images.githubusercontent.com/17312341/120263957-f7b3c900-c2c6-11eb-8902-395a0d5e2385.jpg)

![Screenshot_20210601-104748_OpenKeychain.jpg](https://user-images.githubusercontent.com/17312341/120263974-fda9aa00-c2c6-11eb-8725-ebc5b5de51e4.jpg)

![Screenshot_20210601-104821_OpenKeychain.jpg](https://user-images.githubusercontent.com/17312341/120263981-0306f480-c2c7-11eb-8715-ce981dadeb5c.jpg)

**Comment by lucanaef** [comment]
Thanks for the suggestion! Seems like a cool feature :-) It would also be nice to be able to generate these QR codes (at least for keys that can be found on a keyserver). I've had some spare time this evening and started implementing this. What do you think?


https://user-images.githubusercontent.com/9679062/120377438-67ed3980-c31d-11eb-91f7-32a5d8e1b6f7.MP4

**Comment by lucanaef** [comment]
I know it could be hard to discover the feature, but I really don't want to add another menu entry under the "+" button...

**Comment by reinhart1010** [comment]
I think putting the QR icon on the "Search Keyserver" search bar is 
already nice and relevant. It's also interesting that other mobile PGP 
clients (such as Tesseract/TesserPG) never thought of adding this 
feature, too.

**Comment by reinhart1010** [comment]
I see that this has been committed into https://github.com/lucanaef/PGPro/commit/4d84be2ffa310d733ed655788acb832995d907ac, should I close this as resolved?

**Comment by lucanaef** [comment]
Sure, I'd also like to add a feature to generate those QR codes for keys that can be found on the keyserver but I'll close this issue for now. Thanks again for the suggestion!
