### ISSUE TITLE
Hiding keypad

### ISSUE THREAD

**Issue by mwid2020** [lucanaef/PGPro#5]
Hi,
first: great move to create an open source app for iOS for PGP encrypten/decryption ! That was needed ! 

When editing a message for encryption, it is not easily possible to hide the keypad again to access the bottom controls bar. Any simple common way to hide the keypad (selecting a public key does it ... but it's not so intuitive.

**Comment by lucanaef** [comment]
The intended way is to use a swipe gesture (see GIF) but I agree that this is not easily discoverable. Do you have a suggestion for a more intuitive solution?

![IMG_0796](https://user-images.githubusercontent.com/9679062/80289988-f57d5380-8731-11ea-84c1-2ea629c4b984.GIF)

**Comment by mwid2020** [comment]
Indeed, I did not come across this gesture, which works. It is actually the same behaviour as in the iOS Notes App, as I have seen now.
I guess the common method on iOS is to have an additional "Done" button on the top right, but it would crash your design ;-)

**Comment by lucanaef** [comment]
I'm thinking about adding an additional keyboard dismiss button (see screenshot). While this is not really the native iOS way, I have seen this done in other apps and quite like the approach.

![keyboard_dismiss_button](https://user-images.githubusercontent.com/9679062/82221929-29523000-9910-11ea-8a6c-021acb8fc69f.png)

**Comment by lucanaef** [comment]
This will be included in the upcoming 2020.3 update.
