### ISSUE TITLE
Bug: Cannot import asc file.

### ISSUE THREAD

**Issue by rhearmas** [lucanaef/PGPro#8]
As the title says, I cannot import `asc` files into the application from Files or in the application itself; the "No new keys imported" dialog box appears when trying to do so.

**Comment by lucanaef** [comment]
I've tried to improve the wording of the error message to at least make clear what the issue with the key is. This will be included in the upcoming 2020.3 update. 
If there are any problems after that, feel free to open another Issue :-) 
Thanks again for pointing it out!
