### ISSUE TITLE
Import priv key after matching pub key

### ISSUE THREAD

**Issue by damanti-me** [lucanaef/PGPro#9]
I got the issue that I can’t import a key pair one after another. First the pub key and then the priv key e.g. 
just one of them. Preproduction with any key pair. 
iPhone 8 
13.4.1
App Version. 2020.02

**Comment by damanti-me** [comment]
Solved by importing both together

**Comment by lucanaef** [comment]
This is a known limitation but should at least result in a useful error message. 
Thanks for pointing it out!

**Comment by damanti-me** [comment]
Thanks for the response! 
Unfortunately the attempt to import a key encrypted according to ed25519 fails. Is only RSA possible?

**Comment by lucanaef** [comment]
In the current version the cryptography framework doesn't support elliptic-curve cryptography. See also https://github.com/krzyzanowskim/ObjectivePGP/pull/141.

**Comment by lucanaef** [comment]
I tried to improve the wording in the current version (2020.3). Therefore I'll close this issue for now.
